import web3 from './web3';

const address = '0x80FF401ea96c2E4a9Dcbc7549B16a28AdaA8D58A';

const abi = [{"constant":true,"inputs":[],"name":"getReportsCount","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"manager","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"pickWinner","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"getPlayers","outputs":[{"name":"","type":"address[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"getReports","outputs":[{"components":[{"name":"recipient","type":"address"},{"name":"name","type":"string"},{"name":"dateOfDeath","type":"string"},{"name":"timeOfDeath","type":"string"},{"name":"placeOfDeath","type":"string"},{"name":"city","type":"string"},{"name":"postalCode","type":"string"},{"name":"country","type":"string"},{"name":"province","type":
"string"},{"name":"medicalCauseOfDeath","type":"string"},{"name":"meansOfDeath","type":"string"}],"name":"","type":"tuple[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"reports","outputs":[{"name":"recipient","type":"address"},{"name":"name","type":"string"},{"name":"dateOfDeath","type":"string"},{"name":"timeOfDeath","type":"string"},{"name":"placeOfDeath","type":"string"},{"name":"city","type":"string"},{"name":"postalCode","type":"string"},{"name":"country","type":"string"},{"name":"province","type":"string"},{"name":"medicalCauseOfDeath","type":"string"},{"name":"meansOfDeath","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"recipient","type":"address"},
{"name":"name","type":"string"},{"name":"dateOfDeath","type":"string"},{"name":"timeOfDeath","type":"string"},{"name":"placeOfDeath","type":"string"},{"name":"city","type":"string"},{"name":"postalCode","type":"string"},{"name":"country","type":"string"},{"name":"province","type":"string"},{"name":"medicalCauseOfDeath","type":"string"},{"name":"meansOfDeath","type":"string"}],"name":"createReport","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"enter","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"players","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"}]

export default new web3.eth.Contract(abi, address);

